---

- name: chrony.conf の配置
  become: yes
  template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'
  notify: chrony の reload
