---

- name: Set vm.swappiness to 1 in /etc/sysctl.conf
  become: yes
  sysctl:
    name: vm.swappiness
    value: 1
    state: present
    reload: yes

- name: install MySQL-python
  become: yes
  yum:
   name: MySQL-python
   state: present

- name: removes anonymous user account for localhost
  mysql_user:
    name: ''
    host: localhost
    state: absent
