---

- name: yum install
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ rhel_packages }}"

- name: epel repository の追加
  become: yes
  yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_version.split('.')[0] }}.noarch.rpm"
    state: present

- name: epel repo の無効化
  become: yes
  replace:
    dest: /etc/yum.repos.d/epel.repo
    regexp: "enabled=.*"
    replace: "enabled=0"

- name: yum install with epel repository
  become: yes
  yum:
    name: "{{ item }}"
    state: present
    enablerepo: epel
  with_items: "{{ epel_packages }}"
