---

- name: configure ssh
  become: yes
  copy:
    src: ssh_config
    dest: "/etc/ssh/ssh_config"
    mode: 0644
    owner: root
    group: root

- name: disable password authenctication, challenge response authenctication, and root login
  become: yes
  copy:
    src: sshd_config
    dest: "/etc/ssh/sshd_config"
    mode: 0644
    owner: root
    group: root
  notify: restart sshd
