---

- name: install epel repo
  become: yes
  yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_version.split('.')[0] }}.noarch.rpm"
    state: present

- name: yum install certbot
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - certbot
