---

- name: /etc/profile.d/ へ各種 bash 設定の配置
  become: yes
  template:
    src: "{{ item }}.j2"
    dest: /etc/profile.d/{{ item }}
    mode: 0644
    owner: root
    group: root
  with_items:
    - aliases.sh
    - crontab.sh
    - ls.sh
